{% set name = "qsum" %}
{% set version = "0.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: '0d5fae32a914b799ac0c269d4868b7d55c95ef88ba4eaf34c2ccb40ae3f6b97c'

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  files:
    - pytest.ini
    - mypy.ini
    - .pylintrc
  requires:
    - pytest >=4.4.0
    - pytest-pylint
    - python {{ python_min }}
  imports:
    - qsum
    - qsum.core
    - qsum.core.logic
    - qsum.core.constants
    - qsum.data
    - qsum.types
    - qsum.util
  commands:
    - python -c "import qsum; qsum.test(use_default_args=False)"

about:
  home: https://github.com/QCoding/qsum
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Python Checksumming Library'
  description: 'Intuitive and extendable checksumming for python objects'
  dev_url: https://github.com/QCoding/qsum

extra:
  recipe-maintainers:
    - QCoding
